fixed fatal errors of function.
TycheSoftwares/woocommerce-abandoned-cart pull request #916
Opened 2023-08-21 07:19 UTC by nidhitatosaniya

2023-08-23 09:14 UTC, nidhitatosaniya commented on includes/class-wcal-admin-notice.php
> +						);
Fixed In last commit.

2023-08-23 09:41 UTC, pinalj commented on includes/class-wcal-admin-notice.php
> +					<div id='wcal_cron_notice' class='is-dismissible notice notice-info wcal-cron-notice'>
@nidhitatosaniya - can u pls add code to make the notice dismissible? i.e. if the user dismisses the notice we should save that and ensure the notice is not displayed unless the field value is changed again.

2023-08-23 09:41 UTC, pinalj requested changes
Pls make changes as requested.

2023-08-25 05:36 UTC, pinalj approved these changes

2023-08-25 05:38 UTC, merged